name: Block Merge Requests on Labels

on:
  pull_request:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  update_pr_state:
    runs-on: ubuntu-latest

    steps:
    - name: Check for WIP label
      id: check-label
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        script: |
          const context = github.context;
          const repo = context.repo;
          const pullRequest = context.payload.pull_request;
          const labels = pullRequest.labels.map(label => label.name);
          
          if (!labels.includes('WIP')) {
            console.log('Label "WIP" not found, exiting');
            process.exit(0);
          }
          
    - name: Update PR State
      if: steps.check-label.outputs.exit-code == 0
      uses: actions/github-script@v2
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        script: |
          const context = github.context;
          const state = 'failure';
          const description = 'The CI has failed';
          const repo = context.repo;

          const pullRequest = context.payload.pull_request;
          const prNumber = pullRequest.number;

          await github.pulls.createReview({
            owner: repo.owner,
            repo: repo.repo,
            pull_number: prNumber,
            body: description,
            event: 'REQUEST_CHANGES'
          });
          await github.repos.createStatus({
            owner: repo.owner,
            repo: repo.repo,
            sha: pullRequest.head.sha,
            state: state,
            description: description,
            context: 'Continuous Integration'
          });