name: Block Merge Requests on Labels

on:
  pull_request:
    types: [labeled]


jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if merge request contains blocked label
        id: check_label
        if: contains(github.event.pull_request.labels.*.name, 'WIP')
        run: |
          echo "This pull request contains a blocked label and cannot be merged."
          echo "TO_BLOCK=yes" >> $GITHUB_OUTPUT
          
      - name: Set Pull Request Status
        uses: actions/labeler@v4
        uses: actions/github-script@v6
        if: ${{ steps.check_label.outputs.TO_BLOCK == 'yes' }}
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo
            const octokit = new github.GitHub(github-token)
            octokit.pulls.update({
              ...repository,
              pull_number: pullRequest.number,
              state: 'failure',
            })
