name: Block Merge Requests on Labels

on:
  pull_request:
    types: [labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}


jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if merge request contains blocked label
        id: check_label
        if: contains(github.event.pull_request.labels.*.name, 'WIP')
        run: |
          echo "This pull request contains a blocked label and cannot be merged."
          exit 0
          
      - name: Set Pull Request Status
        uses: actions/github-script@v6
        if: ${{ steps.check_label.outputs.TO_BLOCK == 0 }}
         env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        script: |
          const context = github.context;
          const state = 'failure';
          const description = 'The CI has failed';
          const repo = context.repo;

          const pullRequest = context.payload.pull_request;
          const prNumber = pullRequest.number;

          await github.pulls.createReview({
            owner: repo.owner,
            repo: repo.repo,
            pull_number: prNumber,
            body: description,
            event: 'REQUEST_CHANGES'
          });
          await github.repos.createStatus({
            owner: repo.owner,
            repo: repo.repo,
            sha: pullRequest.head.sha,
            state: state,
            description: description,
            context: 'Continuous Integration'
          });
